version: '3.7'

services:

  webapp_project_name:
    restart: always
    container_name: webapp_project_name
    build:
      context: front/web
      dockerfile: Dockerfile
    ports:
      - 8822:80
    deploy:
      resources:
        limits:
          cpus: ".21"
          memory: 518M
        reservations:
          memory: 518M


  api_project_name:
    restart: always
    container_name: api_project_name
    build:
      context: back/demo
      dockerfile: Dockerfile
    ports:
      - 2288:8080
    volumes: 
      - ./logs:/logs
    deploy:
      resources:
        limits:
          cpus: ".21"
          memory: 518M
        reservations:
          memory: 518M
